In [1]:
## Uxarray 
!pip install uxarray

Defaulting to user installation because normal site-packages is not writeable


In [2]:
import uxarray as ux
import numpy as np
import xoak
from matplotlib import pyplot as plt
from cmocean import cm 

In [3]:
path1 = "../../FESOM_data/channel/"
mesh_fn = "fesom.mesh.diag.nc"
u_path = 'u.fesom.2005.nc'
v_path = 'v.fesom.2005.nc'
#grid_path = "../../test/meshfiles/ugrid/outCSne30/outCSne30.ug"
#data_path = "../../test/meshfiles/ugrid/outCSne30/outCSne30_vortex.nc"

In [4]:
uxds = ux.open_dataset(path1+mesh_fn, path1+u_path)
uxds


<xarray.UxDataset> Size: 1GB
Dimensions:  (nz1: 40, time: 365, n_face: 21120)
Coordinates:
  * nz1      (nz1) float64 320B 4.519 14.01 24.45 ... 3.459e+03 3.814e+03
  * time     (time) datetime64[ns] 3kB 2005-01-01T23:50:00 ... 2005-12-31T23:...
Dimensions without coordinates: n_face
Data variables:
    u        (time, nz1, n_face) float32 1GB ...

In [5]:
uxds.uxgrid

<uxarray.Grid>
Original Grid Type: UGRID
Grid Dimensions:
  * n_node: 10608
  * n_edge: 31728
  * n_face: 21120
  * n_max_face_nodes: 3
  * two: 2
  * n_nodes_per_face: (21120,)
Grid Coordinates (Spherical):
  * node_lon: (10608,)
  * node_lat: (10608,)
Grid Coordinates (Cartesian):
Grid Connectivity Variables:
  * face_node_connectivity: (21120, 3)
  * face_edge_connectivity: (21120, 3)
  * face_face_connectivity: (21120, 3)
  * edge_node_connectivity: (31728, 2)
  * edge_face_connectivity: (31728, 2)
Grid Descriptor Variables:
  * n_nodes_per_face: (21120,)

In [6]:
uxds.uxgrid.node_lon

<xarray.DataArray 'node_lon' (n_node: 10608)> Size: 85kB
array([0.    , 0.0469, 0.    , ..., 4.4062, 4.4531, 4.4062])
Dimensions without coordinates: n_node
Attributes:
    long_name:      longitude
    standard_name:  longitude
    units:          degrees_east

In [7]:
u=uxds["u"].compute()
u

<xarray.UxDataArray 'u' (time: 365, nz1: 40, n_face: 21120)> Size: 1GB
array([[[ 4.9888296e-03,  1.8726081e-03,  5.4882965e-03, ...,
         -4.1953032e-04,  3.0431913e-03,  2.6572179e-03],
        [ 4.9860151e-03,  1.8695410e-03,  5.4881074e-03, ...,
         -2.8813095e-04,  3.0379717e-03,  2.6303199e-03],
        [ 4.9823816e-03,  1.8634194e-03,  5.4823016e-03, ...,
         -4.6001136e-05,  2.9306670e-03,  2.5087290e-03],
        ...,
        [ 2.0460954e-03, -1.1014328e-03,  3.5123462e-03, ...,
          2.9300167e-03,  5.9693954e-03,  4.6279817e-03],
        [ 2.1169791e-03, -1.0221309e-03,  3.3988203e-03, ...,
          3.4115957e-03,  5.4347869e-03,  4.0091891e-03],
        [ 2.7573016e-03, -4.0029857e-04,  3.2348547e-03, ...,
          3.8109703e-03,  5.0520771e-03,  3.6529526e-03]],

       [[ 1.6392737e-03, -1.8111211e-03,  2.0791495e-03, ...,
         -2.9441277e-03,  1.4815327e-03,  1.3637191e-03],
        [ 1.6361012e-03, -1.8141354e-03,  2.0818273e-03, ...,
         -2.8063483e-03,  1.4668838e-03,  1.3260504e-03],
        [ 1.6322954e-03, -1.8197660e-03,  2.0785611e-03, ...,
         -2.5585266e-03,  1.3456022e-03,  1.1874354e-03],
...
        [ 1.1365030e-02,  1.5035513e-02,  1.1233598e-02, ...,
          4.3215983e-02,  4.6530012e-02,  4.7852922e-02],
        [ 1.2300528e-02,  1.5954627e-02,  1.1504344e-02, ...,
          4.2688154e-02,  4.6526063e-02,  4.7839254e-02],
        [ 1.3441855e-02,  1.7075565e-02,  1.1963540e-02, ...,
          4.2371709e-02,  4.6594769e-02,  4.7902685e-02]],

       [[ 1.2252290e-02,  1.5862988e-02,  1.1224110e-02, ...,
          5.4464582e-02,  5.3058192e-02,  5.5232156e-02],
        [ 1.2248907e-02,  1.5866438e-02,  1.1252062e-02, ...,
          5.4200199e-02,  5.3240214e-02,  5.5381563e-02],
        [ 1.2249189e-02,  1.5882144e-02,  1.1296183e-02, ...,
          5.3830519e-02,  5.3382780e-02,  5.5439707e-02],
        ...,
        [ 1.5045659e-02,  1.8606100e-02,  1.4814168e-02, ...,
          4.4841185e-02,  4.8394140e-02,  4.9536299e-02],
        [ 1.5969804e-02,  1.9510411e-02,  1.5109558e-02, ...,
          4.4282362e-02,  4.8364270e-02,  4.9506459e-02],
        [ 1.7085707e-02,  2.0606939e-02,  1.5605913e-02, ...,
          4.3953735e-02,  4.8411332e-02,  4.9547579e-02]]], dtype=float32)
Coordinates:
  * nz1      (nz1) float64 320B 4.519 14.01 24.45 ... 3.459e+03 3.814e+03
  * time     (time) datetime64[ns] 3kB 2005-01-01T23:50:00 ... 2005-12-31T23:...
Dimensions without coordinates: n_face
Attributes:
    description:  zonal velocity
    long_name:    zonal velocity
    units:        m/s
    location:     face
    mesh:         fesom_mesh

In [8]:
ux=u.isel(nz1=0).sel(time='2005-01-01')
ux

<xarray.UxDataArray 'u' (time: 1, n_face: 21120)> Size: 84kB
array([[ 0.00498883,  0.00187261,  0.0054883 , ..., -0.00041953,
         0.00304319,  0.00265722]], dtype=float32)
Coordinates:
    nz1      float64 8B 4.519
  * time     (time) datetime64[ns] 8B 2005-01-01T23:50:00
Dimensions without coordinates: n_face
Attributes:
    description:  zonal velocity
    long_name:    zonal velocity
    units:        m/s
    location:     face
    mesh:         fesom_mesh

In [9]:
ux=ux.isel(time=0, drop=True)
ux

<xarray.UxDataArray 'u' (n_face: 21120)> Size: 84kB
array([ 0.00498883,  0.00187261,  0.0054883 , ..., -0.00041953,
        0.00304319,  0.00265722], dtype=float32)
Coordinates:
    nz1      float64 8B 4.519
Dimensions without coordinates: n_face
Attributes:
    description:  zonal velocity
    long_name:    zonal velocity
    units:        m/s
    location:     face
    mesh:         fesom_mesh

In [10]:
ux.plot(vmin=-1, vmax=1,
       cmap="coolwarm",
    figsize=(6, 10),
    add_colorbar=True,
    title="Zonal Velocity at the Surface (2005-01-01)")

:Image   [x,y]   (x_y u)